site_name: KraftwerK Servicecenter
site_url: https://kraftwerk.shop/servicecenter
site_description: Technische Dokumentation für Produkte, Module und Systeme

hooks:
  - hooks/reorder_i18n_top_nav.py

docs_dir: docs

theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: "#f29100"
      accent: "#ff9a01"
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.tabbed

plugins:
  - search
  - awesome-pages
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      fallback_to_default: false
      reconfigure_search: true
      languages:
        - locale: de
          name: Deutsch
          build: true
          default: true
          theme:
            language: de
        - locale: en
          name: English
          build: true
          theme:
            language: en
        - locale: es
          name: Español
          build: true
          theme:
            language: es
        - locale: it
          name: Italiano
          build: true
          theme:
            language: it
        - locale: cs
          name: Čeština
          build: true
          theme:
            language: cs
        - locale: da
          name: Dansk
          build: true
          theme:
            language: da

  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - scripts/header-back.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kraftwerk-zone
